package so.wwb.creditbox.model.enums.base;

import org.soul.commons.support.IModuleType;

public enum BoModuleType implements IModuleType {

    //登录-登出
    PASSPORT_LOGIN(ModuleType.PASSPORT_LOGIN.getCode(), ModuleType.PASSPORT_LOGIN.getTrans()),
    PASSPORT_LOGOUT(ModuleType.PASSPORT_LOGOUT.getCode(), ModuleType.PASSPORT_LOGOUT.getTrans()),
    PASSPORT_LOGIN_FAIL(ModuleType.PASSPORT_LOGIN_FAIL.getCode(), ModuleType.PASSPORT_LOGIN_FAIL.getTrans()),

    PLAYER_PASSWORD_UPDATE(ModuleType.PLAYER_PASSWORD_UPDATE.getCode(), ModuleType.PLAYER_PASSWORD_UPDATE.getTrans()),
    PLAYER_REALNAME_UPDATE(ModuleType.PLAYER_REALNAME_UPDATE.getCode(), ModuleType.PLAYER_REALNAME_UPDATE.getTrans()),

    //账号
    USER_ACCOUNT_BOSS_SUB_ADD(ModuleType.PASSPORT_LOGOUT.getCode(), ModuleType.PASSPORT_LOGOUT.getTrans()),
    USER_ACCOUNT_SH_ADD(ModuleType.USER_ACCOUNT_SH_ADD.getCode(), ModuleType.USER_ACCOUNT_SH_ADD.getTrans()),
    USER_ACCOUNT_ME_ADD(ModuleType.USER_ACCOUNT_ME_ADD.getCode(), ModuleType.USER_ACCOUNT_ME_ADD.getTrans()),
    USER_ACCOUNT_DI_ADD(ModuleType.USER_ACCOUNT_DI_ADD.getCode(), ModuleType.USER_ACCOUNT_DI_ADD.getTrans()),
    USER_ACCOUNT_UPDATE(ModuleType.USER_ACCOUNT_UPDATE.getCode(), ModuleType.USER_ACCOUNT_UPDATE.getTrans()),

    USER_MINUTE_INFO_UPDATE(ModuleType.USER_MINUTE_INFO_UPDATE.getCode(), ModuleType.USER_MINUTE_INFO_UPDATE.getTrans()),
    USER_STATUS(ModuleType.USER_STATUS.getCode(), ModuleType.USER_STATUS.getTrans()),
    USER_STATUS_FREEZE(ModuleType.USER_STATUS_FREEZE.getCode(), ModuleType.USER_STATUS_FREEZE.getTrans()),
    USER_STATUS_FREEZE_TRUE(ModuleType.USER_STATUS_FREEZE_TRUE.getCode(), ModuleType.USER_STATUS_FREEZE_TRUE.getTrans()),
    USER_STATUS_FREEZE_FALSE(ModuleType.USER_STATUS_FREEZE_FALSE.getCode(), ModuleType.USER_STATUS_FREEZE_FALSE.getTrans()),
    USER_STATUS_DISABLE_OR_NORMAL(ModuleType.USER_STATUS_DISABLE_OR_NORMAL.getCode(), ModuleType.USER_STATUS_DISABLE_OR_NORMAL.getTrans()),
    USER_PASSWORD_UPDATE(ModuleType.USER_PASSWORD_UPDATE.getCode(), ModuleType.USER_PASSWORD_UPDATE.getTrans()),
    USER_PERMISSIONPWD_UPDATE(ModuleType.USER_PERMISSIONPWD_UPDATE.getCode(), ModuleType.USER_PERMISSIONPWD_UPDATE.getTrans()),

    USER_ACCOUNT_RESET_AUTHENTICATION_KEY(ModuleType.USER_ACCOUNT_RESET_AUTHENTICATION_KEY.getCode(), ModuleType.USER_ACCOUNT_RESET_AUTHENTICATION_KEY.getTrans()),
    COMMON_UPDATE_REMARK(ModuleType.COMMON_UPDATE_REMARK.getCode(), ModuleType.COMMON_UPDATE_REMARK.getTrans()),


    TAKE_PLAY_UPDATE_MONEY(ModuleType.TAKE_PLAY_UPDATE_MONEY.getCode(), ModuleType.TAKE_PLAY_UPDATE_MONEY.getTrans()),
    TAKE_PLAY_UPDATE_NUMBER(ModuleType.TAKE_PLAY_UPDATE_NUMBER.getCode(), ModuleType.TAKE_PLAY_UPDATE_NUMBER.getTrans()),
    TAKE_PLAY_UPDATE_SYS_PARAM(ModuleType.TAKE_PLAY_UPDATE_SYS_PARAM.getCode(), ModuleType.TAKE_PLAY_UPDATE_SYS_PARAM.getTrans()),


    //彩票/游戏
    LOTTERY_OPEN_NUMBER(ModuleType.LOTTERY_OPEN_NUMBER.getCode(), ModuleType.LOTTERY_OPEN_NUMBER.getTrans()),
    LOTTERY_ADJUST(ModuleType.LOTTERY_ADJUST.getCode(), ModuleType.LOTTERY_ADJUST.getTrans()),
    LOTTERY_PAYOUT(ModuleType.LOTTERY_PAYOUT.getCode(), ModuleType.LOTTERY_PAYOUT.getTrans()),
    LOTTERY_RECALCULATE(ModuleType.LOTTERY_RECALCULATE.getCode(), ModuleType.LOTTERY_RECALCULATE.getTrans()),
    LOTTERY_REVOKE(ModuleType.LOTTERY_REVOKE.getCode(), ModuleType.LOTTERY_REVOKE.getTrans()),
    LOTTERY_REVOCATION(ModuleType.LOTTERY_REVOCATION.getCode(), ModuleType.LOTTERY_REVOCATION.getTrans()),
    LOTTERY_MAKE_UP(ModuleType.LOTTERY_MAKE_UP.getCode(), ModuleType.LOTTERY_MAKE_UP.getTrans()),
    LOTTERY_RESULT(ModuleType.LOTTERY_RESULT.getCode(), ModuleType.LOTTERY_RESULT.getTrans()),
    LOTTERY_GATHER_CONF(ModuleType.LOTTERY_GATHER_CONF.getCode(), ModuleType.LOTTERY_GATHER_CONF.getTrans()),

    LOTTERY_HANDICAP_EDIT(ModuleType.LOTTERY_HANDICAP_EDIT.getCode(), ModuleType.LOTTERY_HANDICAP_EDIT.getTrans()),

    LOTTERY_SORT(ModuleType.LOTTERY_SORT.getCode(), ModuleType.LOTTERY_SORT.getTrans()),
    LOTTERY_SYNC(ModuleType.LOTTERY_SYNC.getCode(), ModuleType.LOTTERY_SYNC.getTrans()),
    LOTTERY_TAKE_OFF(ModuleType.LOTTERY_TAKE_OFF.getCode(), ModuleType.LOTTERY_TAKE_OFF.getTrans()),
    LOTTERY_GENRE(ModuleType.LOTTERY_GENRE.getCode(), ModuleType.LOTTERY_GENRE.getTrans()),
    LOTTERY_STATUS(ModuleType.LOTTERY_STATUS.getCode(), ModuleType.LOTTERY_STATUS.getTrans()),
    LOTTERY_ADD_OR_UPDATE(ModuleType.LOTTERY_ADD_OR_UPDATE.getCode(), ModuleType.LOTTERY_ADD_OR_UPDATE.getTrans()),
    LOTTERY_UPDATE(ModuleType.LOTTERY_UPDATE.getCode(), ModuleType.LOTTERY_UPDATE.getTrans()),
    LOTTERY_DELETE(ModuleType.LOTTERY_DELETE.getCode(), ModuleType.LOTTERY_DELETE.getTrans()),
    LOTTERY_HOT(ModuleType.LOTTERY_HOT.getCode(), ModuleType.LOTTERY_HOT.getTrans()),
    LOTTERY_NEW(ModuleType.LOTTERY_NEW.getCode(), ModuleType.LOTTERY_NEW.getTrans()),
    LOTTERY_ZODIAC(ModuleType.LOTTERY_ZODIAC.getCode(), ModuleType.LOTTERY_ZODIAC.getTrans()),
    LOTTERY_RULE(ModuleType.LOTTERY_RULE.getCode(), ModuleType.LOTTERY_RULE.getTrans()),

    LOTTERY_TYPE_SORT(ModuleType.LOTTERY_TYPE_SORT.getCode(), ModuleType.LOTTERY_TYPE_SORT.getTrans()),
    LOTTERY_TYPE_ADD_OR_UPDATE(ModuleType.LOTTERY_TYPE_ADD_OR_UPDATE.getCode(), ModuleType.LOTTERY_TYPE_ADD_OR_UPDATE.getTrans()),
    LOTTERY_TYPE_ADD(ModuleType.LOTTERY_TYPE_ADD.getCode(), ModuleType.LOTTERY_TYPE_ADD.getTrans()),
    LOTTERY_TYPE_UPDATE(ModuleType.LOTTERY_TYPE_UPDATE.getCode(), ModuleType.LOTTERY_TYPE_UPDATE.getTrans()),
    LOTTERY_TYPE_DELETE(ModuleType.LOTTERY_TYPE_DELETE.getCode(), ModuleType.LOTTERY_TYPE_DELETE.getTrans()),
    LOTTERY_TYPE_STATUS(ModuleType.LOTTERY_TYPE_STATUS.getCode(), ModuleType.LOTTERY_TYPE_STATUS.getTrans()),

    LOTTERY_ODD_UPDATE(ModuleType.LOTTERY_ODD_UPDATE.getCode(), ModuleType.LOTTERY_ODD_UPDATE.getTrans()),
    LOTTERY_QUOTA_UPDATE(ModuleType.LOTTERY_QUOTA_UPDATE.getCode(), ModuleType.LOTTERY_QUOTA_UPDATE.getTrans()),

    CALL_BILL_RAKEBACK(ModuleType.CALL_BILL_RAKEBACK.getCode(), ModuleType.CALL_BILL_RAKEBACK.getTrans()),
    CALL_BILL_SALARY(ModuleType.CALL_BILL_SALARY.getCode(), ModuleType.CALL_BILL_SALARY.getTrans()),
    CALL_BILL_DIVIDEN(ModuleType.CALL_BILL_DIVIDEN.getCode(), ModuleType.CALL_BILL_DIVIDEN.getTrans()),
    CALL_REPORT_CAME(ModuleType.CALL_REPORT_CAME.getCode(), ModuleType.CALL_REPORT_CAME.getTrans()),
    CALL_REPORT_OPERATE(ModuleType.CALL_REPORT_OPERATE.getCode(), ModuleType.CALL_REPORT_OPERATE.getTrans()),
    CALL_BILL_RETREAT(ModuleType.CALL_BILL_RETREAT.getCode(), ModuleType.CALL_BILL_RETREAT.getTrans()),
    CALL_REPORT_BUSINESS(ModuleType.CALL_REPORT_BUSINESS.getCode(), ModuleType.CALL_REPORT_BUSINESS.getTrans()),


    CONTENT_SITE_ANNOUNCEMENT_ADD_OR_UPDATE(ModuleType.CONTENT_SITE_ANNOUNCEMENT_ADD_OR_UPDATE.getCode(), ModuleType.CONTENT_SITE_ANNOUNCEMENT_ADD_OR_UPDATE.getTrans()),
    CONTENT_SITE_ANNOUNCEMENT_DELETE(ModuleType.CONTENT_SITE_ANNOUNCEMENT_DELETE.getCode(), ModuleType.CONTENT_SITE_ANNOUNCEMENT_DELETE.getTrans()),
    CONTENT_SITE_ANNOUNCEMENT_DISPLAY(ModuleType.CONTENT_SITE_ANNOUNCEMENT_DISPLAY.getCode(), ModuleType.CONTENT_SITE_ANNOUNCEMENT_DISPLAY.getTrans()),
    CONTENT_SITE_ANNOUNCEMENT_SORT(ModuleType.CONTENT_SITE_ANNOUNCEMENT_SORT.getCode(), ModuleType.CONTENT_SITE_ANNOUNCEMENT_SORT.getTrans()),

    CONTENT_SITE_DOMAIN_ADD(ModuleType.CONTENT_SITE_DOMAIN_ADD.getCode(), ModuleType.CONTENT_SITE_DOMAIN_ADD.getTrans()),
    CONTENT_SITE_DOMAIN_DELETE(ModuleType.CONTENT_SITE_DOMAIN_DELETE.getCode(), ModuleType.CONTENT_SITE_DOMAIN_DELETE.getTrans()),
    CONTENT_SITE_DOMAIN_UPDATE(ModuleType.CONTENT_SITE_DOMAIN_UPDATE.getCode(), ModuleType.CONTENT_SITE_DOMAIN_UPDATE.getTrans()),
    CONTENT_SITE_DOMAIN_STATUS(ModuleType.CONTENT_SITE_DOMAIN_STATUS.getCode(), ModuleType.CONTENT_SITE_DOMAIN_STATUS.getTrans()),
    CONTENT_SITE_DOMAIN_RESOLVE_STATUS(ModuleType.CONTENT_SITE_DOMAIN_RESOLVE_STATUS.getCode(), ModuleType.CONTENT_SITE_DOMAIN_RESOLVE_STATUS.getTrans()),

    CONTENT_SITE_DISTRIBUTOR_DOMAIN_ADD(ModuleType.CONTENT_SITE_DISTRIBUTOR_DOMAIN_ADD.getCode(), ModuleType.CONTENT_SITE_DISTRIBUTOR_DOMAIN_ADD.getTrans()),
    CONTENT_SITE_SHAREHOLDER_DOMAIN_ADD(ModuleType.CONTENT_SITE_SHAREHOLDER_DOMAIN_ADD.getCode(), ModuleType.CONTENT_SITE_SHAREHOLDER_DOMAIN_ADD.getTrans()),
    CONTENT_SITE_BOSSS_DOMAIN_ADD(ModuleType.CONTENT_SITE_BOSSS_DOMAIN_ADD.getCode(), ModuleType.CONTENT_SITE_BOSSS_DOMAIN_ADD.getTrans()),

    CONTENT_SITE_DISTRIBUTOR_DOMAIN_UPDATE(ModuleType.CONTENT_SITE_DISTRIBUTOR_DOMAIN_UPDATE.getCode(), ModuleType.CONTENT_SITE_DISTRIBUTOR_DOMAIN_UPDATE.getTrans()),

    CONTENT_SITE_AGENT_DOMAIN_ADD(ModuleType.CONTENT_SITE_AGENT_DOMAIN_ADD.getCode(), ModuleType.CONTENT_SITE_AGENT_DOMAIN_ADD.getTrans()),
    CONTENT_SITE_AGENT_DOMAIN_UPDATE(ModuleType.CONTENT_SITE_AGENT_DOMAIN_UPDATE.getCode(), ModuleType.CONTENT_SITE_AGENT_DOMAIN_UPDATE.getTrans()),
    CONTENT_PROFIT_ADD_OR_UPDATE(ModuleType.CONTENT_PROFIT_ADD_OR_UPDATE.getCode(), ModuleType.CONTENT_PROFIT_ADD_OR_UPDATE.getTrans()),

    //域名站点
    SITE_DOMAIN_ADD(ModuleType.SITE_DOMAIN_ADD.getCode(), ModuleType.SITE_DOMAIN_ADD.getTrans()),
    SITE_DOMAIN_UPDATE(ModuleType.SITE_DOMAIN_UPDATE.getCode(), ModuleType.SITE_DOMAIN_UPDATE.getTrans()),
    SITE_DOMAIN_ISDISABLE(ModuleType.SITE_DOMAIN_ISDISABLE.getCode(), ModuleType.SITE_DOMAIN_ISDISABLE.getTrans()),
    SITE_DOMAIN_WHITELIST_ADD_OR_UPDATE(ModuleType.SITE_DOMAIN_WHITELIST_ADD_OR_UPDATE.getCode(), ModuleType.SITE_DOMAIN_WHITELIST_ADD_OR_UPDATE.getTrans()),
    SITE_DOMAIN_BLACKLIST_ADD_OR_UPDATE(ModuleType.SITE_DOMAIN_BLACKLIST_ADD_OR_UPDATE.getCode(), ModuleType.SITE_DOMAIN_BLACKLIST_ADD_OR_UPDATE.getTrans()),
    SITE_DOMAIN_WHITELIST_DELETE(ModuleType.SITE_DOMAIN_WHITELIST_DELETE.getCode(), ModuleType.SITE_DOMAIN_WHITELIST_DELETE.getTrans()),
    SITE_DOMAIN_BLACKLIST_DELETE(ModuleType.SITE_DOMAIN_BLACKLIST_DELETE.getCode(), ModuleType.SITE_DOMAIN_BLACKLIST_DELETE.getTrans()),
    SITE_DOMAIN_MAINTENANCE(ModuleType.SITE_DOMAIN_MAINTENANCE.getCode(), ModuleType.SITE_DOMAIN_MAINTENANCE.getTrans()),
    SITE_DOMAIN_TO_BOUND(ModuleType.SITE_DOMAIN_TO_BOUND.getCode(), ModuleType.SITE_DOMAIN_TO_BOUND.getTrans()),
    SITE_DOMAIN_BOUNDED(ModuleType.SITE_DOMAIN_BOUNDED.getCode(), ModuleType.SITE_DOMAIN_BOUNDED.getTrans()),
    SITE_DOMAIN_DELETE(ModuleType.SITE_DOMAIN_DELETE.getCode(), ModuleType.SITE_DOMAIN_DELETE.getTrans()),
    SITE_DOMAIN_CHECK_SUCCESS(ModuleType.SITE_DOMAIN_CHECK_SUCCESS.getCode(), ModuleType.SITE_DOMAIN_CHECK_SUCCESS.getTrans()),
    SITE_DOMAIN_CHECK_FAIL(ModuleType.SITE_DOMAIN_CHECK_FAIL.getCode(), ModuleType.SITE_DOMAIN_CHECK_FAIL.getTrans()),
    SITE_DOMAIN_BOUNDED_FAIL(ModuleType.SITE_DOMAIN_BOUNDED_FAIL.getCode(), ModuleType.SITE_DOMAIN_BOUNDED_FAIL.getTrans()),


    SITE_BOSS_UPDATE(ModuleType.SITE_BOSS_UPDATE.getCode(), ModuleType.SITE_BOSS_UPDATE.getTrans()),
    SITE_BOSS_STATUS(ModuleType.SITE_BOSS_STATUS.getCode(), ModuleType.SITE_BOSS_STATUS.getTrans()),

    SITE_BOSS_DOMAIN_BLACKLIST_ADD_OR_UPDATE(ModuleType.SITE_BOSS_DOMAIN_BLACKLIST_ADD_OR_UPDATE.getCode(), ModuleType.SITE_BOSS_DOMAIN_BLACKLIST_ADD_OR_UPDATE.getTrans()),


    SITE_SH_UPDATE(ModuleType.SITE_SH_UPDATE.getCode(), ModuleType.SITE_SH_UPDATE.getTrans()),
    SITE_SH_DOMAIN_ADD_OR_UPDATE(ModuleType.SITE_SH_DOMAIN_ADD_OR_UPDATE.getCode(), ModuleType.SITE_SH_DOMAIN_ADD_OR_UPDATE.getTrans()),
    SITE_SH_DOMAIN_ISDISABLE(ModuleType.SITE_SH_DOMAIN_ISDISABLE.getCode(), ModuleType.SITE_SH_DOMAIN_ISDISABLE.getTrans()),
    SITE_SH_STATUS(ModuleType.SITE_SH_STATUS.getCode(), ModuleType.SITE_SH_STATUS.getTrans()),

    SITE_ME_STATUS(ModuleType.SITE_ME_STATUS.getCode(), ModuleType.SITE_ME_STATUS.getTrans()),
    SITE_ME_UPDATE(ModuleType.SITE_ME_UPDATE.getCode(), ModuleType.SITE_ME_UPDATE.getTrans()),

    SITE_GROUP_ADD(ModuleType.SITE_GROUP_ADD.getCode(), ModuleType.SITE_GROUP_ADD.getTrans()),
    SITE_GROUP_UPDATE(ModuleType.SITE_GROUP_UPDATE.getCode(), ModuleType.SITE_GROUP_UPDATE.getTrans()),
    SITE_GROUP_DELETE(ModuleType.SITE_GROUP_DELETE.getCode(), ModuleType.SITE_GROUP_DELETE.getTrans()),



    //系统 901-1100
    SYS_CONFINE_WHITELIST_IP_ADD_OR_UPDATE(ModuleType.SYS_CONFINE_WHITELIST_IP_ADD_OR_UPDATE.getCode(), ModuleType.SYS_CONFINE_WHITELIST_IP_ADD_OR_UPDATE.getTrans()),
    SYS_CONFINE_WHITELIST_IP_DELETE(ModuleType.SYS_CONFINE_WHITELIST_IP_DELETE.getCode(), ModuleType.SYS_CONFINE_WHITELIST_IP_DELETE.getTrans()),
    SYS_CONFINE_BLACKLIST_IP_ADD_OR_UPDATE(ModuleType.SYS_CONFINE_BLACKLIST_IP_ADD_OR_UPDATE.getCode(), ModuleType.SYS_CONFINE_BLACKLIST_IP_ADD_OR_UPDATE.getTrans()),
    SYS_CONFINE_BLACKLIST_IP_DELETE(ModuleType.SYS_CONFINE_BLACKLIST_IP_DELETE.getCode(), ModuleType.SYS_CONFINE_BLACKLIST_IP_DELETE.getTrans()),

    SYS_ACCOUNT_DOMAIN(ModuleType.SYS_ACCOUNT_DOMAIN.getCode(), ModuleType.SYS_ACCOUNT_DOMAIN.getTrans()),
    SYS_SETTING_VOICE(ModuleType.SYS_SETTING_VOICE.getCode(), ModuleType.SYS_SETTING_VOICE.getTrans()),
    SYS_MESSAGE(ModuleType.SYS_MESSAGE.getCode(), ModuleType.SYS_MESSAGE.getTrans()),
    SYS_CUSTOMER_SERVICE_PARAMS_ADD_OR_UPDATE(ModuleType.SYS_CUSTOMER_SERVICE_PARAMS_ADD_OR_UPDATE.getCode(), ModuleType.SYS_CUSTOMER_SERVICE_PARAMS_ADD_OR_UPDATE.getTrans()),
    SYS_YZM_PARAMS_ADD_OR_UPDATE(ModuleType.SYS_YZM_PARAMS_ADD_OR_UPDATE.getCode(), ModuleType.SYS_YZM_PARAMS_ADD_OR_UPDATE.getTrans()),
    SYS_PLAYER_REGISTER_MODE_ADD(ModuleType.SYS_PLAYER_REGISTER_MODE_ADD.getCode(), ModuleType.SYS_PLAYER_REGISTER_MODE_ADD.getTrans()),
    SYS_TONE_PARAMS_UPDATE(ModuleType.SYS_TONE_PARAMS_UPDATE.getCode(), ModuleType.SYS_TONE_PARAMS_UPDATE.getTrans()),
    SYS_TONE_PARAMS_ACTIVE(ModuleType.SYS_TONE_PARAMS_ACTIVE.getCode(), ModuleType.SYS_TONE_PARAMS_ACTIVE.getTrans()),

    SYS_CREATE_SITE(ModuleType.SYS_CREATE_SITE.getCode(), ModuleType.SYS_CREATE_SITE.getTrans()),

    SYS_PAY_JAR_ADD_OR_UPDATE(ModuleType.SYS_PAY_JAR_ADD_OR_UPDATE.getCode(), ModuleType.SYS_PAY_JAR_ADD_OR_UPDATE.getTrans()),
    SYS_PAY_JAR_VERSION_UPDATE(ModuleType.SYS_PAY_JAR_VERSION_UPDATE.getCode(), ModuleType.SYS_PAY_JAR_VERSION_UPDATE.getTrans()),
    SYS_PAY_JAR_DELETE(ModuleType.SYS_PAY_JAR_DELETE.getCode(), ModuleType.SYS_PAY_JAR_DELETE.getTrans()),
    SYS_PAY_API_ADD_OR_UPDATE(ModuleType.SYS_PAY_API_ADD_OR_UPDATE.getCode(), ModuleType.SYS_PAY_API_ADD_OR_UPDATE.getTrans()),
    SYS_PAY_API_DELETE(ModuleType.SYS_PAY_API_DELETE.getCode(), ModuleType.SYS_PAY_API_DELETE.getTrans()),
    SYS_PAY_API_ISUSE(ModuleType.SYS_PAY_API_ISUSE.getCode(), ModuleType.SYS_PAY_API_ISUSE.getTrans()),

    SYS_APP_ADD_OR_UPDATE(ModuleType.SYS_APP_ADD_OR_UPDATE.getCode(), ModuleType.SYS_APP_ADD_OR_UPDATE.getTrans()),
    SYS_APP_KEY_ADD_OR_UPDATE(ModuleType.SYS_APP_KEY_ADD_OR_UPDATE.getCode(), ModuleType.SYS_APP_KEY_ADD_OR_UPDATE.getTrans()),
    SYS_APP_KEY_STATUS(ModuleType.SYS_APP_KEY_STATUS.getCode(), ModuleType.SYS_APP_KEY_STATUS.getTrans()),
    SYS_APP_UPDATE_DELETE(ModuleType.SYS_APP_UPDATE_DELETE.getCode(), ModuleType.SYS_APP_UPDATE_DELETE.getTrans()),
    SYS_APP_REEOR_LOG_UPDATE(ModuleType.SYS_APP_REEOR_LOG_UPDATE.getCode(), ModuleType.SYS_APP_REEOR_LOG_UPDATE.getTrans()),

    SYS_ANN_ADD_OR_UPDATE(ModuleType.SYS_ANN_ADD_OR_UPDATE.getCode(), ModuleType.SYS_ANN_ADD_OR_UPDATE.getTrans()),
    SYS_ANN_DELETE(ModuleType.SYS_ANN_DELETE.getCode(), ModuleType.SYS_ANN_DELETE.getTrans()),
    SYS_MSG_ADD(ModuleType.SYS_MSG_ADD.getCode(), ModuleType.SYS_MSG_ADD.getTrans()),

    SYS_UPDATE_VERIFICATION(ModuleType.SYS_UPDATE_VERIFICATION.getCode(), ModuleType.SYS_UPDATE_VERIFICATION.getTrans()),
    SYS_UPDATE_NAME_VERIFICATION(ModuleType.SYS_UPDATE_NAME_VERIFICATION.getCode(), ModuleType.SYS_UPDATE_NAME_VERIFICATION.getTrans()),
    SYS_UPDATE_BANKCARDNUMBER_VERIFICATION(ModuleType.SYS_UPDATE_BANKCARDNUMBER_VERIFICATION.getCode(), ModuleType.SYS_UPDATE_BANKCARDNUMBER_VERIFICATION.getTrans()),
    SYS_UPDATE_CHECK_REAL_NAME(ModuleType.SYS_UPDATE_CHECK_REAL_NAME.getCode(), ModuleType.SYS_UPDATE_CHECK_REAL_NAME.getTrans()),
    SYS_UPDATE_API(ModuleType.SYS_UPDATE_API.getCode(), ModuleType.SYS_UPDATE_API.getTrans()),
    SYS_UPDATE_CHECK_MOBILE(ModuleType.SYS_UPDATE_CHECK_MOBILE.getCode(), ModuleType.SYS_UPDATE_CHECK_MOBILE.getTrans()),
    SYS_UPDATE_CHECK_WEIXIN(ModuleType.SYS_UPDATE_CHECK_WEIXIN.getCode(), ModuleType.SYS_UPDATE_CHECK_WEIXIN.getTrans()),
    SYS_UPDATE_DEMO(ModuleType.SYS_UPDATE_DEMO.getCode(), ModuleType.SYS_UPDATE_DEMO.getTrans()),

    SYS_UPDATE_CHECK_PAYEE_BANK_ALIPAY(ModuleType.SYS_UPDATE_CHECK_PAYEE_BANK_ALIPAY.getCode(), ModuleType.SYS_UPDATE_CHECK_PAYEE_BANK_ALIPAY.getTrans()),
    SYS_UPDATE_CHECK_PAYEE_BANK_WEIXIN(ModuleType.SYS_UPDATE_CHECK_PAYEE_BANK_WEIXIN.getCode(), ModuleType.SYS_UPDATE_CHECK_PAYEE_BANK_WEIXIN.getTrans()),

    SYS_UPDATE_API_TRANSFER_SITE(ModuleType.SYS_UPDATE_API_TRANSFER_SITE.getCode(), ModuleType.SYS_UPDATE_API_TRANSFER_SITE.getTrans()),

    //运维
    OPS_TASK_SCHEDULE_SERVICE_RUN(ModuleType.OPS_TASK_SCHEDULE_SERVICE_RUN.getCode(), ModuleType.OPS_TASK_SCHEDULE_SERVICE_RUN.getTrans()),



    ;

    private String code;
    private String trans;

    BoModuleType(String code, String trans) {
        this.code = code;
        this.trans = trans;
    }

    @Override
    public String getCode() {
        return code;
    }

    @Override
    public String getTrans() {
        return trans;
    }
}
